// AUTO-GENERATED by scripts/gen-deployments.mjs — DO NOT EDIT.
// Inlined from src/deployments/*.json (the deployment artifacts written by the Foundry deploy script).
export const deployments = {
  1: {
    "caip2": "eip155:1",
    "chainId": 1,
    "contracts": {
      "AsseteraECS": "0xf045d3FE81C14d8c13DbaB0b03a4Ea1505e499ad",
      "AsseteraPrimarySales": "0xF62757dd232DC7582A5d46F62aAcDb6B739223Dc",
      "Forwarder": "0x2244B33a97f91284D53d0A12d42F237927C3DBf7"
    },
    "implementations": {
      "AsseteraECS": "0xcb2D5e22b2de63bA0958d5D7c39D7216B84803c2",
      "AsseteraPrimarySales": "0xCb0ef38528fd695116B745722d7d03485584175F"
    },
    "metadata": {
      "admin": "0x5c682CFC1ffd09a1CA2c04165C34E14aB8810c0E",
      "deployBlock": 25795740,
      "deployTimestamp": 1787221787,
      "deployer": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27",
      "feeSigner": "0x291e286F83F16bFafCB92d50Ab1C6028BF87d537",
      "kycSigner": "0x4D54a843e1ad6929b4Db3B7a3e9Db9f1493e2729",
      "operator": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27",
      "relayer": "0xa410D91d7a07c3ebc3984E36B9a9a2D16C4029c3",
      "settlementSigner": "0x749964a0e112C29fa55448530634BA727c53EFd1"
    },
    "namespace": "eip155"
  },
  137: {
    "caip2": "eip155:137",
    "chainId": 137,
    "contracts": {
      "AsseteraECS": "0xf045d3FE81C14d8c13DbaB0b03a4Ea1505e499ad",
      "AsseteraPrimarySales": "0xF62757dd232DC7582A5d46F62aAcDb6B739223Dc",
      "Forwarder": "0x2244B33a97f91284D53d0A12d42F237927C3DBf7"
    },
    "implementations": {
      "AsseteraECS": "0xcb2D5e22b2de63bA0958d5D7c39D7216B84803c2",
      "AsseteraPrimarySales": "0xA96707072A53dDCE9205530C5132aE8EEF0222e0"
    },
    "metadata": {
      "admin": "0x5c682CFC1ffd09a1CA2c04165C34E14aB8810c0E",
      "deployBlock": 92344157,
      "deployTimestamp": 1787221263,
      "deployer": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27",
      "feeSigner": "0x291e286F83F16bFafCB92d50Ab1C6028BF87d537",
      "kycSigner": "0x4D54a843e1ad6929b4Db3B7a3e9Db9f1493e2729",
      "operator": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27",
      "relayer": "0xa410D91d7a07c3ebc3984E36B9a9a2D16C4029c3",
      "settlementSigner": "0x749964a0e112C29fa55448530634BA727c53EFd1"
    },
    "namespace": "eip155"
  },
  80002: {
    "caip2": "eip155:80002",
    "chainId": 80002,
    "contracts": {
      "AsseteraECS": "0xf045d3FE81C14d8c13DbaB0b03a4Ea1505e499ad",
      "AsseteraPrimarySales": "0xF62757dd232DC7582A5d46F62aAcDb6B739223Dc",
      "Forwarder": "0x2244B33a97f91284D53d0A12d42F237927C3DBf7",
      "MockRWA": "0xECe9f75Eb6af58B7c70773BbC5922E49fD65F3E0",
      "MockUSDC": "0x85D7B2569b3d69320F05A4FFB140Ca4521989A15"
    },
    "implementations": {
      "AsseteraECS": "0xcb2D5e22b2de63bA0958d5D7c39D7216B84803c2",
      "AsseteraPrimarySales": "0xC0c7F32806a8C99287151B7F4886Ef2CDEFf2C7d"
    },
    "metadata": {
      "admin": "0x7bEfCf24Ca3E457B100F769bf24FF31d698970ac",
      "deployBlock": 45229125,
      "deployTimestamp": 1787047566,
      "deployer": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27",
      "feeSigner": "0xf238Fa055b2E5b5a1C751A9C7D524F265719163b",
      "kycSigner": "0xd1782B6351d09dF9968B0b97108379B33908cC09",
      "operator": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27",
      "relayer": "0xa410D91d7a07c3ebc3984E36B9a9a2D16C4029c3",
      "settlementSigner": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27"
    },
    "namespace": "eip155"
  },
  11155111: {
    "caip2": "eip155:11155111",
    "chainId": 11155111,
    "contracts": {
      "AsseteraECS": "0xf045d3FE81C14d8c13DbaB0b03a4Ea1505e499ad",
      "AsseteraPrimarySales": "0xF62757dd232DC7582A5d46F62aAcDb6B739223Dc",
      "Forwarder": "0x2244B33a97f91284D53d0A12d42F237927C3DBf7",
      "MockRWA": "0xECe9f75Eb6af58B7c70773BbC5922E49fD65F3E0",
      "MockUSDC": "0x85D7B2569b3d69320F05A4FFB140Ca4521989A15"
    },
    "implementations": {
      "AsseteraECS": "0xcb2D5e22b2de63bA0958d5D7c39D7216B84803c2",
      "AsseteraPrimarySales": "0xC0c7F32806a8C99287151B7F4886Ef2CDEFf2C7d"
    },
    "metadata": {
      "admin": "0x18be62A39daDCe169e05eA45E956124537214310",
      "deployBlock": 11514803,
      "deployTimestamp": 1787052660,
      "deployer": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27",
      "feeSigner": "0x7F61F6004E54a41C6BD4a8656A47ABc7Ab27829b",
      "kycSigner": "0x076ca734BFfF2dbe8cdfc5E760880F87942457D1",
      "operator": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27",
      "relayer": "0xa410D91d7a07c3ebc3984E36B9a9a2D16C4029c3",
      "settlementSigner": "0xDEaDFA8BC247c921745a2D4B6216eFaAdece9D27"
    },
    "namespace": "eip155"
  },
} as const;
